apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: How to update images to fixed release versions ; SHA/tag to be updated on each release
resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=98b313aa1db6764623deb3abdc02f1e380bf41df
- https://github.com/redhat-appstudio/jvm-build-service/deploy/base?ref=98b313aa1db6764623deb3abdc02f1e380bf41df
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=98b313aa1db6764623deb3abdc02f1e380bf41df
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=98b313aa1db6764623deb3abdc02f1e380bf41df

generatorOptions:
  disableNameSuffixHash: true


#
# NB: From operator/overlays/dev-template
images:
  - name: hacbs-jvm-operator
    newName: quay.io/ncross/hacbs-jvm-controller
    newTag: dev

# NB: From overlays/dev-template
patches:
# TODO: Remove first (quaytoken) once https://github.com/redhat-appstudio/jvm-build-service/pull/915 is merged
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/secret/optional
      value: true
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: quay.io/ncross/hacbs-jvm-build-request-processor:dev
  target:
    kind: Task
    name: maven
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: quay.io/ncross/hacbs-jvm-build-request-processor:dev
  target:
    kind: Task
    name: gradle
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: S3_SYNC_ENABLED
          value: "true"
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- path: config.yaml
- path: system-config.yaml
