apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=3fd26d5925e09eb41d146bc271333f3510a00cb7
- https://github.com/redhat-appstudio/jvm-build-service/deploy/base?ref=3fd26d5925e09eb41d146bc271333f3510a00cb7
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=3fd26d5925e09eb41d146bc271333f3510a00cb7
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=3fd26d5925e09eb41d146bc271333f3510a00cb7
# TODO Do we need the cluster monitoring from operator/overlays/dev-template? Could reference the files directly.

# NB: From operator/overlays/dev-template
images:
  - name: hacbs-jvm-operator
    newName: quay.io/${JBS_QUAY_IMAGE}/hacbs-jvm-controller
    newTag: dev

# NB: From overlays/dev-template
patches:
# TODO: Remove first (quaytoken) once https://github.com/${JBS_QUAY_IMAGE}/jvm-build-service/pull/915 is merged
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/secret/optional
      value: true
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: quay.io/${JBS_QUAY_IMAGE}/hacbs-jvm-build-request-processor:dev
  target:
    kind: Task
    name: maven
- patch: |-
    - op: replace
      path: /spec/steps/2/image
      value: quay.io/${JBS_QUAY_IMAGE}/hacbs-jvm-build-request-processor:dev
  target:
    kind: Task
    name: gradle
# TODO:
# - patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env"
#       value:
#         - name: S3_SYNC_ENABLED
#           value: "true"
#   target:
#     kind: Deployment
#     name: hacbs-jvm-operator
- path: config.yaml
- path: system-config.yaml
