apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=51e82b4a2a0bc6d234627b4374b7e7126f8474aa
- https://github.com/redhat-appstudio/jvm-build-service/deploy/base?ref=51e82b4a2a0bc6d234627b4374b7e7126f8474aa
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=51e82b4a2a0bc6d234627b4374b7e7126f8474aa
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=51e82b4a2a0bc6d234627b4374b7e7126f8474aa
- https://github.com/redhat-appstudio/jvm-build-service/deploy/console/base?ref=51e82b4a2a0bc6d234627b4374b7e7126f8474aa
# TODO Do we need the cluster monitoring from operator/overlays/dev-template? Could reference the files directly.

# NB: From operator/overlays/dev-template
images:
  - name: hacbs-jvm-operator
    newName: quay.io/${JBS_QUAY_IMAGE}/hacbs-jvm-controller
    newTag: dev
  - name: hacbs-jvm-console
    newName: quay.io/${JBS_QUAY_IMAGE}/jbs-management-console
    newTag: dev

# NB: From operator/overlays/dev-template and console/overlays/dev-template
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
    name: hacbs-jvm-console
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: S3_SYNC_ENABLED
          value: "true"
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- path: config.yaml
- path: system-config.yaml
