apiVersion: v1
kind: Secret
metadata:
  name: jvm-build-maven-repo-aws-secrets
  namespace: jvm-build-workloads
type: Opaque
stringData:
  awsaccesskey: |
    ${AWS_ACCESS_KEY_ID}
  awssecretkey: |
    ${AWS_SECRET_ACCESS_KEY}
  awsregion: |
    ${AWS_PROFILE}
