apiVersion: v1
kind: Secret
metadata:
  name: jvm-build-s3-secrets
  namespace: jvm-build-workloads
type: Opaque
stringData:
  awsaccesskey: |
    ${AWS_ACCESS_KEY_ID}
  awssecretkey: |
    ${AWS_SECRET_ACCESS_KEY}
  awsregion: |
    us-east-1
